- src/recorder.rb
- remove repeated `attr_accessor :events`
- `ruby -c src/recorder.rb`
> Fix duplicate attr_accessor declaration

- src/recorder.rb
- require `fileutils` in the recorder
- create the trace folder with `FileUtils.mkdir_p`
- `ruby -c src/recorder.rb`
> Ensure trace folder exists

- src/recorder.rb
- avoid error if load_flow is called on an unseen path
- document placeholder `load_exprs` method
- `ruby -c src/recorder.rb`
- `ruby -c src/trace.rb`
> Fix unused load_flow logic

- .editorconfig
- clarify why Markdown files retain trailing spaces in `.editorconfig`
- `git status --short`
> Add comment on markdown whitespace

- .github/workflows/ci.yml
- use `cachix/install-nix-action` instead of running inside a container
- `ruby -Itest test/test_tracer.rb`
> Fix Nix CI job

- .gitattributes
- .gitignore
- Justfile
- test/benchmarks/fixtures/heavy_work_trace.json
- test/benchmarks/programs/heavy_work.rb
- test/benchmarks/run_benchmark.rb
- manage benchmark fixtures with git-lfs
- add a benchmark program that calculates prime numbers
- parametrize `run_benchmark.rb` and use system cmp when available
- add `bench` task with optional name argument to `Justfile`
- record benchmark results with `run_benchmark.rb`
- `just test` *(fails: command not found)*
- `ruby -Itest test/test_tracer.rb`
> Add benchmark directory with sample program

- .gitignore
- Rakefile
- codetracer-ruby-recorder.gemspec
- ext/native_tracer/Cargo.toml
- ext/native_tracer/README.md
- ext/native_tracer/extconf.rb
- ext/native_tracer/src/lib.rs
- rename native library to `codetracer_ruby_native_recorder`
- package native extension with `rb_sys`
- provide publishing instructions in the extension README
- `ruby -Itest test/test_tracer.rb`
> Add packaging for native extension

- README.md
- src/native_trace.rb
- provide minimal CLI `src/native_trace.rb` that loads the compiled native tracer
- document CLI usage in the README
- `just test`
> Add native tracer command-line utility

- README.md
- ext/native_tracer/README.md
- src/native_trace.rb
- src/recorder.rb
- src/trace.rb
- test/benchmarks/run_benchmark.rb
- test/test_tracer.rb
- add `--out-dir` option for tracer utilities
- default to `CODETRACER_RUBY_RECORDER_OUT_DIR` or current dir
- rename env variable in code, docs and tests
- document new usage and env var in README
- `just test`
- `just bench`
> Add CLI out-dir option and rename env var

- examples/selective_tracing.rb
- gems/native-tracer/ext/native_tracer/src/lib.rs
- gems/native-tracer/lib/native_trace.rb
- introduce `RubyRecorder` Ruby class in native extension
- allow enabling/disabling tracing and flushing to a directory
- update CLI and example to use the new API
- `just test`
> Integrate runtime_tracing crate

- gems/native-tracer/ext/native_tracer/src/lib.rs
- use Ruby typed data APIs for `Recorder` to avoid manual ivar pointer
- define `rb_data_type_t` descriptor and allocation
- detach the pointer in `flush_trace`
- `just test`
> Improve recorder storage using typed data

- gems/native-tracer/ext/native_tracer/Cargo.toml
- gems/native-tracer/lib/native_trace.rb
- test/test_tracer.rb
- build native tracer as cdylib
- allow native tracer script to fall back if the extension fails
- run native tracer for tests
- only check textual output in tests
- use both pure-ruby and native tracer; only compare JSON trace for pure tracer
- `just test`
> Use native tracer in test suite

- gems/native-tracer/ext/native_tracer/src/lib.rs
- import missing `rb_raise` and `rb_eIOError`
- align `flush_to_dir` error type with tracer utilities
- `just test`
> Fix native tracer compilation

- examples/selective_tracing.rb
- gems/native-tracer/ext/native_tracer/src/lib.rs
- Remove the use of Mutex (Ruby already provides a global lock)
- Remove the pointless init function
- Add error handling
> fix: Clean up some of the cruft generated by Codex

- .github/workflows/ci.yml
- gems/native-tracer/lib/native_trace.rb
- test/test_tracer.rb
- ensure native tracer extension can be loaded across operating systems
- check in tests that the native tracer produced a non-empty trace
- `just test`
> Fix native tracer loading and assert non-empty trace

- gems/native-tracer/ext/native_tracer/src/lib.rs
- gems/native-tracer/lib/native_trace.rb
- test/test_tracer.rb
- implement Ruby event capture in Rust using runtime_tracing
- hook into I/O methods to emit Write events
- record method parameters and local variables
- load target program without wrapper so class names match
- ensure trace output matches the pure Ruby tracer
- `just test`
> Implement native tracer prototype

- gems/native-tracer/ext/native_tracer/src/lib.rs
- cache commonly used Ruby symbols during recorder initialization
- update native tracer to use cached IDs
- `just test`
> Implement intern caching in native recorder

- gems/pure-ruby-tracer/lib/recorder.rb
- gems/pure-ruby-tracer/lib/trace.rb
- conditionally emit tracer debug output based on `CODETRACER_RUBY_TRACER_DEBUG`
- cache env lookup to reduce overhead
- restore warning from native tracer
- `just test`
> Guard Ruby tracer output by env var

- .github/workflows/ci.yml
- Justfile
- MAINTANERS.md
- test/benchmarks/README.md
- test/benchmarks/run_benchmark.rb
- integrate SVG report generation in benchmark runner
- drop old script and update Justfile/CI to use new option
- document benchmark usage in MAINTANERS and README
- `just test`
- `just bench heavy_work`
- `just bench heavy_work reports/benchmark_report.svg`
> Add benchmark SVG report in CI

- gems/pure-ruby-tracer/lib/recorder.rb
- gems/pure-ruby-tracer/lib/trace.rb
- remove global DEBUG_TRACER constant
- let `Tracer` accept a `debug` flag and read the ENV variable during initialization
- propagate debug flag to `TraceRecord`
- update debug checks in tracer and recorder
- `just test`
> Pass debug mode through Tracer constructor

- Justfile
- test/benchmarks/run_benchmarks.rb
- allow specifying a glob of benchmarks to run instead of a directory
- record results for plain Ruby execution, native tracer and pure Ruby tracer
- compare traces structurally via JSON and print consolidated table
- update `just bench` recipe to pass a glob
- `just test`
- `just bench` *(fails: One or more traces differ from reference!)*
> Add flexible benchmark glob runner

- gems/native-tracer/ext/native_tracer/src/lib.rs
- Added safer conversions in the native tracer to avoid panics while serialising uninitialised objects. The conversion of `self` now uses a protected `to_s` call and argument registration precedes it to match the pure tracer.
- add `value_to_string_safe` using `rb_protect`
- skip errors when fetching method parameters and serialising `self`
- adjust call event logic ordering
> Handle more Ruby types safely

- MAINTAINERS.md
- gems/native-tracer/ext/native_tracer/README.md
- scripts/publish_gems.rb
- publish a generic Ruby gem in `publish_gems.rb`
- update maintainer docs about the new gem
- document how to build and push the fallback gem in the extension readme
- `just test`
> Add ruby platform gem publishing

- gems/native-tracer/codetracer-ruby-recorder.gemspec
- gems/pure-ruby-tracer/codetracer_pure_ruby_recorder.gemspec
- test/test_tracer.rb
- adjust gemspecs to include prebuilt extension and drop references outside of gem directories
- add test verifying the native gem can be built and installed
- also test installation of the pure-ruby tracer gem
- `just test`
> Add gem installation test

- gems/pure-ruby-tracer/lib/trace.rb
- unnest `record_step`, `record_event` and `record_exception` from inside `record_return`
- keep alignment of all `Tracer` instance methods
- `just test`
> Move step/event/exception methods

- README.md
- fix a small typo in README (`you enables` -> `you enable`)
- clean up trailing spaces on lines 67 and 89
- `just test`
> Fix README grammar and whitespace

- Justfile
- codetracer/kernel_patches.rb
- test/test_kernel_patches.rb
- include only one shared kernel patches module
- require kernel patches via relative path in tracer scripts
- remove duplicated modules from gem directories
- `just test`
> Fix Kernel patch module installation

- Justfile
- codetracer/kernel_patches.rb
- gems/codetracer-pure-ruby-recorder/lib/trace.rb
- gems/codetracer-ruby-recorder/lib/native_trace.rb
- test/test_kernel_patches.rb
This commit introduces a new module `Codetracer::KernelPatches` to centralize the monkey-patching logic for `Kernel#p`, `Kernel#puts`, and `Kernel#print`.
Key changes:
- Created `codetracer/kernel_patches.rb` for the new module.
- The `Codetracer::KernelPatches` module now manages a list of active tracers.
- Kernel methods are patched only once. Events are dispatched to all registered tracers.
- `install(tracer)` and `uninstall(tracer)` methods allow tracers to register and unregister.
- Original kernel methods are restored when the last tracer is uninstalled.
- Event recording consistently uses `caller_locations(1,1).first` for path and line info.
- Both the pure Ruby tracer (`trace.rb`) and the native tracer (`native_trace.rb`) have been updated to use this shared module.
- Added …
> Refactor: Introduce Codetracer::KernelPatches module

- codetracer/kernel_patches.rb
- test/test_kernel_patches.rb
- simplify Kernel patch restoration logic by using alias_method instead of storing methods
- rename alias methods to avoid polluting the global namespace
- ensure original Kernel methods are restored when the last tracer is removed
- `just test`
> Improve Kernel patch restoration

- gems/codetracer-pure-ruby-recorder/lib/codetracer/kernel_patches.rb
- gems/codetracer-pure-ruby-recorder/lib/trace.rb
- gems/codetracer-ruby-recorder/lib/codetracer/kernel_patches.rb
- gems/codetracer-ruby-recorder/lib/native_trace.rb
- test/fixtures/more_types_trace.json
- test/fixtures/point_representation_trace.json
- test/test_kernel_patches.rb
- remove the shared `codetracer/kernel_patches.rb`
- require kernel patches relative to each gem
- teach `Tracer#record_event` to support 3 arguments
- handle arrays specially when patching `Kernel#p`
- update fixtures for Ruby 3.2 output and re-enable tracer tests
- `just test`
> Fix test suite by loading kernel patches from each gem

- test/test_tracer.rb
- unskip gem installation tests
- use the correct variable when choosing recorder class
- `just test`
> Fix gem installation tests

- src/trace.rb
TODO: puts should be emulated more properly
> fix: Handle more properly print statements `p`, `puts` and `print`
